#!groovy
pipeline {

  agent any

  tools {
    jdk 'jdk 8'
    maven 'vmn 3.8'
  }

  environment {
      BRANCH_NAME=env.GIT_BRANCH.replace("origin/", "")
  }

  stages {
    stage('Verify Pacts') {
      steps {
        dir('product-catalogue') {
           sh 'mvn clean verify'
        }
      }
    }
    stage('Publish Pacts') {
      steps {
        sh 'curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.83/pact-1.88.83-linux-x86_64.tar.gz'
        sh 'tar xzf pact-1.88.83-linux-x86_64.tar.gz'
        dir('pact/bin') {
            sh "./pact-broker publish ../../product-catalogue/target/pacts/ -a ${GIT_COMMIT} -t ${BRANCH_NAME} -b http://localhost:9292 -v true"
        }
      }
    }
    stage('Check Pact Verifications') {
      steps {
        dir('pact/bin') {
          sh "./pact-broker can-i-deploy --retry-while-unknown=4 --retry-interval=10 -a ProductCatalogue -b http://localhost:9292 -e ${GIT_COMMIT} --to prod -v true"
        }
      }
    }
    stage('Deploy') {
      when {
        branch 'master'
      }
      steps {
        echo 'Deploying to prod now...'
      }
    }
  }

}
