#!groovy
pipeline {

  agent any

  tools {
    jdk 'jdk 8'
  }

  environment {
      BRANCH_NAME=env.GIT_BRANCH.replace("origin/", "")
  }

  stages {
    stage('Build') {
      steps {
        dir('messaging-app') {
           sh '../mvnw clean verify'
        }
      }
    }
    stage('Publish Pacts') {
      steps {
        dir('messaging-app') {
           sh '../mvnw pact:publish -Dpact.consumer.version=${GIT_COMMIT} -Dpact.tag=${BRANCH_NAME}'
        }
      }
    }
    stage('Check Pact Verifications') {
      steps {
        dir('messaging-app') {
           sh '../mvnw  pact:can-i-deploy -Dpacticipant=messaging-app'
        }
      }
    }
    stage('Deploy') {
      when {
        branch 'master'
      }
      steps {
        echo 'Deploying to prod now...'
      }
    }
  }

}
