#!groovy
pipeline {

  agent any

  tools {
    jdk 'jdk 8'
    maven 'vmn 3.8'
  }

  environment {
      BRANCH_NAME=env.GIT_BRANCH.replace("origin/", "")
  }

  stages {
    stage('Build') {
      steps {
        dir('messaging-app') {
           sh '../mvnw clean verify'
        }
      }
    }
    stage('Publish Pacts') {
      steps {
        sh 'curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.61.1/pact-1.61.1-linux-x86_64.tar.gz'
        sh 'tar xzf pact-1.61.1-linux-x86_64.tar.gz'
        dir('pact/bin') {
            sh "./pact-broker publish ../../messaging-app/target/pacts/ -a ${GIT_COMMIT} -h ${BRANCH_NAME} -t SIT -b http://pact_broker:9292 -v true"
        }
      }
    }
    stage('Check Pact Verifications') {
      steps {
        dir('messaging-app') {
           sh 'mvn  pact:can-i-deploy -Dpacticipant=messaging-app'
        }
      }
    }
    stage('Deploy') {
      when {
        branch 'master'
      }
      steps {
        echo 'Deploying to prod now...'
      }
    }
  }

}
