#!groovy
pipeline {

  agent any

  tools {
    jdk 'jdk 8'
    maven 'vmn 3.8'
  }

  stages {
    stage ('Build') {
      steps {
        dir('product-service') {
          sh "mvn clean verify"
        }
      }
    }
    stage('Check Pact Verifications') {
      steps {
        sh 'curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.83/pact-1.88.83-linux-x86_64.tar.gz'
        sh 'tar xzf pact-1.88.83-linux-x86_64.tar.gz'
        dir('pact/bin') {
          sh "./pact-broker can-i-deploy -a ProductService -b http://localhost:9292 -e ${GIT_COMMIT}"
        }
      }
    }
    stage('Deploy') {
      when {
        branch 'master'
      }
      steps {
        echo 'Deploying to prod now...'
      }
    }
  }

}